### ISSUE TITLE
test question

### ISSUE THREAD

**Issue by Trueman1997** [huawei-noah/Pretrained-IPT#22]
I put my own test data into /Pretrained-IPT-main/test_data/ in order to check the denoising,then run the following command,but it did not work?can you help me . 

python main.py --dir_data /Pretrained-IPT-main/test_data/ --pretrain /Pretrained-IPT-main/pretrained_model/ --data_test DICM --scale 1 --denoise --sigma 30

Traceback (most recent call last):
  File "main.py", line 37, in <module>
    main()
  File "main.py", line 22, in main
    loader = data.Data(args)
  File "/gaoren/Pretrained-IPT-main/data/__init__.py", line 35, in __init__
    num_workers=args.n_threads,
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by HantingChen** [comment]
You can add "DICM" in https://github.com/huawei-noah/Pretrained-IPT/blob/32ce841c18ca33c31fa15907ac21bbddd1583519/data/__init__.py#L40, and then put the data in /Pretrained-IPT-main/test_data/DICM .
