### ISSUE TITLE
不能使用--save_results 命令

### ISSUE THREAD

**Issue by oneonejia** [huawei-noah/Pretrained-IPT#34]
当使用save_result命令会出现错误
Evaluation:
Traceback (most recent call last):
  File "main.py", line 37, in <module>
    main()
  File "main.py", line 33, in main
    t.test()
  File "C:\Users\Lenovo\Desktop\Pretrained-IPT-main\trainer.py", line 34, in test
    if self.args.save_results: self.ckp.begin_background()
  File "C:\Users\Lenovo\Desktop\Pretrained-IPT-main\utility.py", line 144, in begin_background
    for p in self.process: p.start()
  File "E:\python3.7\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "E:\python3.7\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "E:\python3.7\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "E:\python3.7\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "E:\python3.7\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)

AttributeError: Can't pickle local object 'checkpoint.begin_background.<locals>.bg_target'

C:\Users\Lenovo\Desktop\Pretrained-IPT-main>WARNING: Ignoring invalid distribution -ip (e:\python3.7\lib\site-packages)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\python3.7\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\python3.7\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)

EOFError: Ran out of input

**Comment by HantingChen** [comment]
可以参考https://github.com/sanghyun-son/EDSR-PyTorch/issues/91
