### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by AIisCool** [huawei-noah/Pretrained-IPT#40]
python main.py --dir_data "C:/Pretrained-IPT-main/test_data/benchmark/" --pretrain "C:/Pretrained-IPT-main/model/IPT_denoise30.pt" --data_test "BW" --scale 1 --denoise --sigma 30 --save_results

```
Making a binary: C:/Pretrained-IPT-main/test_data/benchmark/DIV2K\bin\DIV2K_train_HR\000.pt
Traceback (most recent call last):
  File "C:\Pretrained-IPT-main\main.py", line 37, in <module>
    main()
  File "C:\Pretrained-IPT-main\main.py", line 22, in main
    loader = data.Data(args)
  File "C:\Pretrained-IPT-main\data\__init__.py", line 30, in __init__
    self.loader_train = dataloader.DataLoader(
  File "C:\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 268, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "C:\Python39\lib\site-packages\torch\utils\data\sampler.py", line 102, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

**Comment by HantingChen** [comment]
Note: path of images should be like: $MODEL_PATH/benchmark/CBSD68/XXX.png

**Comment by AIisCool** [comment]
Yes I have it like this: C:\Pretrained-IPT-main\test_data\benchmark\BW\000.png

**Comment by HantingChen** [comment]
Maybe you should rename your dataset as CBSD68, since we do not write codes for dataset BW.

**Comment by AIisCool** [comment]
I tried. I thought adding "BW" to this would work? Was in a different issue thread.

`self.loader_test = []
        for d in args.data_test:
            if d in ['Set5', 'Set14', 'B100', 'Urban100', 'Manga109','CBSD68','Rain100L','GOPRO_Large', 'BW']:`

**Comment by HantingChen** [comment]
> I tried. I thought adding "BW" to this would work? Was in a different issue thread.
> 
> `self.loader_test = [] for d in args.data_test: if d in ['Set5', 'Set14', 'B100', 'Urban100', 'Manga109','CBSD68','Rain100L','GOPRO_Large', 'BW']:`

Yes, I think this should work.

Another strightforward solution is to rename 'BW' as 'CBSD68' and set --data_test "CBSD68".

**Comment by AIisCool** [comment]
Tried renaming, same issue unforunately.

```
  File "C:\Pretrained-IPT-main\main.py", line 37, in <module>
    main()
  File "C:\Pretrained-IPT-main\main.py", line 22, in main
    loader = data.Data(args)
  File "C:\Pretrained-IPT-main\data\__init__.py", line 30, in __init__
    self.loader_train = dataloader.DataLoader(
  File "C:\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 268, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "C:\Python39\lib\site-packages\torch\utils\data\sampler.py", line 102, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

**Comment by HantingChen** [comment]
> Tried renaming, same issue unforunately.
> 
> ```
>   File "C:\Pretrained-IPT-main\main.py", line 37, in <module>
>     main()
>   File "C:\Pretrained-IPT-main\main.py", line 22, in main
>     loader = data.Data(args)
>   File "C:\Pretrained-IPT-main\data\__init__.py", line 30, in __init__
>     self.loader_train = dataloader.DataLoader(
>   File "C:\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 268, in __init__
>     sampler = RandomSampler(dataset, generator=generator)
>   File "C:\Python39\lib\site-packages\torch\utils\data\sampler.py", line 102, in __init__
>     raise ValueError("num_samples should be a positive integer "
> ValueError: num_samples should be a positive integer value, but got num_samples=0
> ```

This is strange. Can the codes work well if you using the original CBSD58 dataset?

**Comment by AIisCool** [comment]
> Can the codes work well if you using the original CBSD68 dataset?

If I do --test_only, then yes.

```
100%|###########################################| 39/39 [06:39<00:00, 10.25s/it]
Making model...

Evaluation:
[CBSD68 x1]     PSNR: 38.132 (Best: 38.132 @epoch 1)
Forward: 399.89s

Saving...
Total: 399.89s
```

If I do --save_results, I get the same error.

```
Traceback (most recent call last):
  File "C:\Pretrained-IPT-main\main.py", line 37, in <module>
    main()
  File "C:\Pretrained-IPT-main\main.py", line 22, in main
    loader = data.Data(args)
  File "C:\Pretrained-IPT-main\data\__init__.py", line 30, in __init__
    self.loader_train = dataloader.DataLoader(
  File "C:\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 268, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "C:\Python39\lib\site-packages\torch\utils\data\sampler.py", line 102, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
```
