### ISSUE TITLE
MACOS系统想复现图像去雨功能，如何修改代码可以绕过使用cuda的部分？

### ISSUE THREAD

**Issue by fuhao66** [huawei-noah/Pretrained-IPT#43]

**Comment by fuhao66** [comment]
Traceback (most recent call last):
  File "/Users/liufuhao/Pretrained-IPT/main.py", line 37, in <module>
    main()
  File "/Users/liufuhao/Pretrained-IPT/main.py", line 33, in main
    t.test()
  File "/Users/liufuhao/Pretrained-IPT/trainer.py", line 42, in test
    sr = self.model(rain, idx_scale)
  File "/Users/liufuhao/Anaconda/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/liufuhao/Pretrained-IPT/model/__init__.py", line 58, in forward
    return forward_function(x)
  File "/Users/liufuhao/Pretrained-IPT/model/__init__.py", line 169, in forward_chop
    y_h_cut = self.cut_h(x_h_cut, h, w, h_cut, w_cut, padsize, shave, scale, batchsize)
  File "/Users/liufuhao/Pretrained-IPT/model/__init__.py", line 215, in cut_h
    y_h_cut_unfold.append(P.data_parallel(self.model, x_h_cut_unfold[i*batchsize:(i+1)*batchsize,...], range(self.n_GPUs)).cpu())
  File "/Users/liufuhao/Anaconda/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 208, in data_parallel
    output_device = device_ids[0]
IndexError: range object index out of range

**Comment by HantingChen** [comment]
把代码中 .cuda() 全部去掉即可。
